---
title: "Marilyn Rhapsody Data"
author: "SNF"
date: "12/21/24"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
editor_options: 
  chunk_output_type: console
---




```{r, warning=FALSE, message=FALSE, warning=FALSE, echo=F}
#devtools::install_github('scfurl/m3addon')
rm(list=ls())
knitr::opts_chunk$set(fig.width=8, fig.height=6,
                      echo=FALSE, warning=FALSE, message=FALSE)
knitr::opts_chunk$set(dev.args=list(bg="transparent"))
mounted<-F
str<-strsplit(Sys.info()[4], "\\.")[[1]]
if(any(str %in% "washington")){loc="UW"} else {loc="SCRI"}
if(any(str %in% c("MacDude", "MLRGSM129", "NQ03CG6094"))){loc = "local"}
if(any(str %in% "ip-172-31-17-144")){loc = "AWS_Analysis"}
switch(loc, UW={ROOT_DIR="~"}, 
      SCRI={ROOT_DIR="~/mnt/furlan_s_active"}, 
      local={ROOT_DIR="/Users/sfurlan/Library/CloudStorage/OneDrive-FredHutchinsonCancerCenter/computation"},
      AWS_Analysis={ROOT_DIR="/home/rstudio"},)
if(mounted){ROOT_DIR="~/mnt/furlan_s_active"}
stem<-"Motoko/Marilyn"
DATA_DIR <- file.path(ROOT_DIR, "Analysis", stem, "data")      # SPECIFY HERE
RES_DIR  <- file.path(ROOT_DIR, "Analysis", stem, "res")     # SPECIFY HERE
RMD_DIR  <- file.path(ROOT_DIR, "Analysis", stem, "rmd")     # SPECIFY HERE
CDS_DIR <- file.path(ROOT_DIR, "Analysis", stem, "cds")
FIG_DIR <- file.path(ROOT_DIR, "Analysis", stem, "figs")
ENR_DIR<-file.path(ROOT_DIR, "Bioinformatics Resources", "MSigDB")
SCRIPT_DIR<-file.path(ROOT_DIR, "develop", "SfScripts", "m3")

suppressPackageStartupMessages({
    library(scCustomize)
  library(Seurat)
  library(openxlsx)  
  library(dplyr)
  library(Matrix)
  library(ggplot2)
  #library(rhdf5)
  library(xfun)
  library(pals)
  library(RColorBrewer)
})


xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))


#load_all(file.path(ROOT_DIR, "fstree"))
# Set global ggplot2 properties for making print-scaled PDF panels
SFtheme<-theme_bw(base_size=14) + 
  theme(panel.background = element_rect(fill = "transparent",colour = NA), # or theme_blank()
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    legend.background = element_rect(fill = "transparent"),
    legend.box.background = element_rect(fill = "transparent"), 
    legend.key = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent",colour = NA))
theme_set(SFtheme)

exp_colors<-c("grey85", "orange", "red", "violetred4", "black")

qthresh<-0.05
ethresh<-1.2

```


# Using RSEC (Recursive substitution error correction)
This is a BD method for converting reads per cell to a corrected "molecule per cell" measurement.
```{r, echo=F}
folders<-as.list(list.files(DATA_DIR, include.dirs = T)[grep("_mm$", list.files(DATA_DIR, include.dirs = T))])
#list.files(file.path(DATA_DIR, folders[[1]]))
names(folders)<-1:8

files<-lapply(folders, function(folder){
  folder2<-file.path(DATA_DIR, folder)
  list.files(folder2, full.names = T)[grep("_mm_RSEC_MolsPerCell.csv$", list.files(folder2))]
})
dat<-lapply(files, function(file){
t(as.matrix(data.table::fread(file), rownames=1))})
dat2<-lapply(dat, function(mat){
  rownames(mat)<-sapply(strsplit(rownames(mat), "\\|"), "[[", 1)
  mat
})
mat<-Matrix(do.call(cbind, dat2), sparse=T)
colnames(mat)<-make.unique(colnames(mat))
meta<-data.frame(cell.names=colnames(mat), sample_no=unlist(lapply(1:8, function(x) {
  rep(names(folders)[[x]], ncol(dat[[x]]))})), row.names = colnames(mat))
meta$sample <- factor(meta$sample_no)
levels(meta$sample)<-c(rep("Spl", 2),rep("mLN", 2),rep("LP", 2),rep("EL", 2))
genes<-data.frame(id = sapply(strsplit(rownames(dat[[1]]), "\\|"), "[[", 2), loc= sapply(strsplit(rownames(dat[[1]]), "\\|"), "[[", 3),  gene_short_name=sapply(strsplit(rownames(dat[[1]]), "\\|"), "[[", 1), row.names=make.unique(sapply(strsplit(rownames(dat[[1]]), "\\|"), "[[", 1)))
rownames(genes)<-genes$id
rownames(mat)<-rownames(genes)

seu <- CreateSeuratObject(mat, meta.data = meta)
seu <- seu[,seu$sample %in% c("LP", "EL")]
seu <- NormalizeData(seu, normalization.method = "LogNormalize", scale.factor = 10000)
seu <- FindVariableFeatures(seu, nfeatures = 3000)
seu <- ScaleData(seu)
seu <- RunPCA(seu, features = VariableFeatures(object = seu))
ElbowPlot(seu)
seu <- FindNeighbors(seu, dims = 1:20)
seu <- FindClusters(seu, resolution = 1)
seu <- RunUMAP(seu, dims = 1:20)
DimPlot(seu, group.by = "sample")

```

### Cytolytic genes
```{r}
rownames(seu)<-genes$gene_short_name
FeaturePlot_scCustom(seu, "Nkg7")
FeaturePlot_scCustom(seu, "Prf1")
FeaturePlot_scCustom(seu, "Gzmb")
FeaturePlot_scCustom(seu, "Gzma")
FeaturePlot_scCustom(seu, "Gzmk")
FeaturePlot_scCustom(seu, "Gzmm")
FeaturePlot_scCustom(seu, "Ifng")
FeaturePlot_scCustom(seu, "Il17a")
FeaturePlot_scCustom(seu, "Il17f")
FeaturePlot_scCustom(seu, "Tnfsf10")
FeaturePlot_scCustom(seu, "Fasl")
FeaturePlot_scCustom(seu, "Tbx21")
FeaturePlot_scCustom(seu, "Rorc")
```


## Dotplot
```{r}
genes <- c("Tbx21", "Rorc", "Ifng", "Il17a", "Nkg7", "Gzmb", "Gzma", "Fasl", "Tnfsf10")
scCustomize::DotPlot_scCustom(seu, features = rev(genes), group.by = "sample", flip_axes = T)

```

## All gene names
```{r}
rownames(seu)
```



### Appendix
```{r Appendix,echo=FALSE}
sessionInfo()
getwd()
```